parameters:
#    ipez_web_service.example.class: Ipez\WebServiceBundle\Example

services:
#    ipez_web_service.example:
#        class: %ipez_web_service.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
