Ipez\ProductBundle\Entity\Product:
    type: entity
    table: null
    repositoryClass: Ipez\ProductBundle\Entity\ProductRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        reference:
            type: string
            length: '40'
        tradeName:
            type: string
            length: '60'
        cI:
            type: integer
        type:
            type: integer
        urlImg:
            type: string
            length: '60'
        salesParty:
            type: integer
    lifecycleCallbacks: {  }
