ipez_web_service:
    resource: "@IpezWebServiceBundle/Resources/config/routing.yml"
    prefix:   /

ipez_party:
    resource: "@IpezPartyBundle/Resources/config/routing.yml"
    prefix:   /

ipez_customer:
    resource: "@IpezCustomerBundle/Resources/config/routing.yml"
    prefix:   /

ipez_product:
    resource: "@IpezProductBundle/Resources/config/routing.yml"
    prefix:   /

