Ipez\WebServiceBundle\Entity\Newsletter:
    type: entity
    table: null
    repositoryClass: Ipez\WebServiceBundle\Entity\NewsletterRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        mail:
            type: string
            length: 255
    lifecycleCallbacks: {  }
