ipez_party_homepage:
    pattern:  /party
    defaults: { _controller: IpezPartyBundle:Default:index }
    
ipez_party_create:
    pattern:  /party/new
    defaults: { _controller: IpezPartyBundle:Default:create }

ipez_party_delete:
    pattern:  /party/delete/{id}
    defaults: { _controller: IpezPartyBundle:Default:delete }