ipez_party_homepage:
    pattern:  /party
    defaults: { _controller: IpezPartyBundle:Default:index }
    
ipez_party_create:
    pattern:  /party/new
    defaults: { _controller: IpezPartyBundle:Default:create }
    
ipez_party_update:
    pattern:  /party/update/{id}
    defaults: { _controller: IpezPartyBundle:Default:update }


ipez_party_delete:
    pattern:  /party/delete/{id}
    defaults: { _controller: IpezPartyBundle:Default:delete }
    

ipez_party_confirm:
    pattern:  /party/confirm/{partyId}
    defaults: { _controller: IpezPartyBundle:Default:sendConfirmationParty }

ipez_party_confirmed:
    pattern:  /party/confirmed/{partyId}/{userId}
    defaults: { _controller: IpezPartyBundle:Default:userConfirmParty }
    
