parameters:
#    ipez_party.example.class: Ipez\PartyBundle\Example

services:
#    ipez_party.example:
#        class: %ipez_party.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
