parameters:
#    ipez_product.example.class: Ipez\ProductBundle\Example

services:
#    ipez_product.example:
#        class: %ipez_product.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
