<?php

namespace Ipez\PartyBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TypePartyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypePartyRepository extends EntityRepository
{
}
